require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/bundle'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false
