require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/bundle'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*'

Layout/LineLength:
  Exclude:
  - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 30

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/AndOr:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false
