databases:
  - name: ckia_fm
    region: ohio
    databaseName: ckia_fm_production
    user: ckia_fm
    plan: free

services:
  - type: web
    name: ckia_fm
    region: ohio
    runtime: ruby
    plan: free
    buildCommand: "bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ckia_fm
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
