on: [push]

name: Linting - Rubocop

jobs:
  run:
    runs-on: ubuntu-latest

    setps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup ruby
        uses: ruby/setup-ruby@master

      - name: Install ruby gems
        run: |
          gem install rubocop rubocop-performance rubocop-rails rubocop-rspec --no-document

      - name: Run rubocop
        run: rubocop
