on: [push]

name: Linting

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup ruby
        uses: ruby/setup-ruby@master
        with:
          bundler-cache: true

      - name: Install ruby gems
        run: |
          bundle install --with test

      - name: Run rubocop
        run: bundle exec rubocop

  erblint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup ruby
        uses: ruby/setup-ruby@master
        with:
          bundler-cache: true

      - name: Install ruby gems
        run: |
          gem install erb_lint --no-document

      - name: Run rubocop
        run: erblint app

