on: [push]

name: Tests

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          PGUSER: postgres
          PGPASSWORD: ''
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # env:
    #   RAILS_ENV: test
    steps:
      - name: Install system libs
        run: sudo apt-get -y install libpq-dev
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@master # v1.92
        with:
          bundler-cache: true
      - name: Set up database schema
        run: bundle exec rails db:create
      - name: Run tests
        run: bundle exec rspec -f p
